language: node_js

os:
  - linux
  - windows

node_js:
  - "node"

services:
  - docker

cache:
  directories:
    - "node_modules"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm config set msvs_version 2015 --global;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm config set python C:\Python27\python.exe;

script:
  - npm run compile
  - npm run lint
  - npm run test
