language: node_js

node_js:
  - "v10.12.0"

matrix:
  include:
    - os: linux

    - os: windows
      before_install:
        - choco install python2
        - npm config set python C:/Python27/python.exe --global
        - npm config set msvs_version 2017 --global

matrix:
  include:
    - os: linux

    - os: windows
      before_install:
        - choco install docker-compose
        - choco install python2
        - npm config set python C:/Python27/python.exe --global
        - npm config set msvs_version 2017 --global

services:
  - docker

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run compile
  - npm run lint
  - npm run test:unit
  - npm run test:int
