language: node_js

os:
  - linux
  - windows

node_js:
  - "node"

services:
  - docker

cache:
  directories:
    - "node_modules"

before_install:
  - npm config set msvs_version 2013 --global
  - npm config set python C:\Python27\python.exe

script:
  - npm run compile
  - npm run lint
  - npm run test
