/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.xchangerpc.ChainInfo', null, global);
goog.exportSymbol('proto.xchangerpc.CurrencyInfo', null, global);
goog.exportSymbol('proto.xchangerpc.GetInfoRequest', null, global);
goog.exportSymbol('proto.xchangerpc.GetInfoResponse', null, global);
goog.exportSymbol('proto.xchangerpc.LndChannels', null, global);
goog.exportSymbol('proto.xchangerpc.LndInfo', null, global);
goog.exportSymbol('proto.xchangerpc.XudInfo', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xchangerpc.GetInfoRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xchangerpc.GetInfoRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.xchangerpc.GetInfoRequest.displayName = 'proto.xchangerpc.GetInfoRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xchangerpc.GetInfoRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.xchangerpc.GetInfoRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xchangerpc.GetInfoRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.GetInfoRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xchangerpc.GetInfoRequest}
 */
proto.xchangerpc.GetInfoRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xchangerpc.GetInfoRequest;
  return proto.xchangerpc.GetInfoRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xchangerpc.GetInfoRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xchangerpc.GetInfoRequest}
 */
proto.xchangerpc.GetInfoRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xchangerpc.GetInfoRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xchangerpc.GetInfoRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xchangerpc.GetInfoRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.GetInfoRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xchangerpc.GetInfoResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.xchangerpc.GetInfoResponse.repeatedFields_, null);
};
goog.inherits(proto.xchangerpc.GetInfoResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.xchangerpc.GetInfoResponse.displayName = 'proto.xchangerpc.GetInfoResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.xchangerpc.GetInfoResponse.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xchangerpc.GetInfoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.xchangerpc.GetInfoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xchangerpc.GetInfoResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.GetInfoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, ""),
    xudinfo: (f = msg.getXudinfo()) && proto.xchangerpc.XudInfo.toObject(includeInstance, f),
    chainsList: jspb.Message.toObjectList(msg.getChainsList(),
    proto.xchangerpc.CurrencyInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xchangerpc.GetInfoResponse}
 */
proto.xchangerpc.GetInfoResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xchangerpc.GetInfoResponse;
  return proto.xchangerpc.GetInfoResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xchangerpc.GetInfoResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xchangerpc.GetInfoResponse}
 */
proto.xchangerpc.GetInfoResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 2:
      var value = new proto.xchangerpc.XudInfo;
      reader.readMessage(value,proto.xchangerpc.XudInfo.deserializeBinaryFromReader);
      msg.setXudinfo(value);
      break;
    case 3:
      var value = new proto.xchangerpc.CurrencyInfo;
      reader.readMessage(value,proto.xchangerpc.CurrencyInfo.deserializeBinaryFromReader);
      msg.addChains(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xchangerpc.GetInfoResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xchangerpc.GetInfoResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xchangerpc.GetInfoResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.GetInfoResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getXudinfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.xchangerpc.XudInfo.serializeBinaryToWriter
    );
  }
  f = message.getChainsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.xchangerpc.CurrencyInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string version = 1;
 * @return {string}
 */
proto.xchangerpc.GetInfoResponse.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.xchangerpc.GetInfoResponse.prototype.setVersion = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional XudInfo xudInfo = 2;
 * @return {?proto.xchangerpc.XudInfo}
 */
proto.xchangerpc.GetInfoResponse.prototype.getXudinfo = function() {
  return /** @type{?proto.xchangerpc.XudInfo} */ (
    jspb.Message.getWrapperField(this, proto.xchangerpc.XudInfo, 2));
};


/** @param {?proto.xchangerpc.XudInfo|undefined} value */
proto.xchangerpc.GetInfoResponse.prototype.setXudinfo = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.xchangerpc.GetInfoResponse.prototype.clearXudinfo = function() {
  this.setXudinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.xchangerpc.GetInfoResponse.prototype.hasXudinfo = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated CurrencyInfo chains = 3;
 * @return {!Array.<!proto.xchangerpc.CurrencyInfo>}
 */
proto.xchangerpc.GetInfoResponse.prototype.getChainsList = function() {
  return /** @type{!Array.<!proto.xchangerpc.CurrencyInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.xchangerpc.CurrencyInfo, 3));
};


/** @param {!Array.<!proto.xchangerpc.CurrencyInfo>} value */
proto.xchangerpc.GetInfoResponse.prototype.setChainsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.xchangerpc.CurrencyInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.xchangerpc.CurrencyInfo}
 */
proto.xchangerpc.GetInfoResponse.prototype.addChains = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.xchangerpc.CurrencyInfo, opt_index);
};


proto.xchangerpc.GetInfoResponse.prototype.clearChainsList = function() {
  this.setChainsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xchangerpc.XudInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xchangerpc.XudInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.xchangerpc.XudInfo.displayName = 'proto.xchangerpc.XudInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xchangerpc.XudInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.xchangerpc.XudInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xchangerpc.XudInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.XudInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, ""),
    nodepubkey: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lndbtc: jspb.Message.getFieldWithDefault(msg, 3, false),
    lndltc: jspb.Message.getFieldWithDefault(msg, 4, false),
    raiden: jspb.Message.getFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xchangerpc.XudInfo}
 */
proto.xchangerpc.XudInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xchangerpc.XudInfo;
  return proto.xchangerpc.XudInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xchangerpc.XudInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xchangerpc.XudInfo}
 */
proto.xchangerpc.XudInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodepubkey(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLndbtc(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLndltc(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRaiden(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xchangerpc.XudInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xchangerpc.XudInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xchangerpc.XudInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.XudInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNodepubkey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLndbtc();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getLndltc();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getRaiden();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional string version = 1;
 * @return {string}
 */
proto.xchangerpc.XudInfo.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.xchangerpc.XudInfo.prototype.setVersion = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string nodepubkey = 2;
 * @return {string}
 */
proto.xchangerpc.XudInfo.prototype.getNodepubkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.xchangerpc.XudInfo.prototype.setNodepubkey = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional bool lndbtc = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.xchangerpc.XudInfo.prototype.getLndbtc = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.xchangerpc.XudInfo.prototype.setLndbtc = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional bool lndltc = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.xchangerpc.XudInfo.prototype.getLndltc = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.xchangerpc.XudInfo.prototype.setLndltc = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional bool raiden = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.xchangerpc.XudInfo.prototype.getRaiden = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.xchangerpc.XudInfo.prototype.setRaiden = function(value) {
  jspb.Message.setField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xchangerpc.CurrencyInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xchangerpc.CurrencyInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.xchangerpc.CurrencyInfo.displayName = 'proto.xchangerpc.CurrencyInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xchangerpc.CurrencyInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.xchangerpc.CurrencyInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xchangerpc.CurrencyInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.CurrencyInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    symbol: jspb.Message.getFieldWithDefault(msg, 1, ""),
    chain: (f = msg.getChain()) && proto.xchangerpc.ChainInfo.toObject(includeInstance, f),
    lnd: (f = msg.getLnd()) && proto.xchangerpc.LndInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xchangerpc.CurrencyInfo}
 */
proto.xchangerpc.CurrencyInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xchangerpc.CurrencyInfo;
  return proto.xchangerpc.CurrencyInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xchangerpc.CurrencyInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xchangerpc.CurrencyInfo}
 */
proto.xchangerpc.CurrencyInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbol(value);
      break;
    case 2:
      var value = new proto.xchangerpc.ChainInfo;
      reader.readMessage(value,proto.xchangerpc.ChainInfo.deserializeBinaryFromReader);
      msg.setChain(value);
      break;
    case 3:
      var value = new proto.xchangerpc.LndInfo;
      reader.readMessage(value,proto.xchangerpc.LndInfo.deserializeBinaryFromReader);
      msg.setLnd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xchangerpc.CurrencyInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xchangerpc.CurrencyInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xchangerpc.CurrencyInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.CurrencyInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getChain();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.xchangerpc.ChainInfo.serializeBinaryToWriter
    );
  }
  f = message.getLnd();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.xchangerpc.LndInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string symbol = 1;
 * @return {string}
 */
proto.xchangerpc.CurrencyInfo.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.xchangerpc.CurrencyInfo.prototype.setSymbol = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional ChainInfo chain = 2;
 * @return {?proto.xchangerpc.ChainInfo}
 */
proto.xchangerpc.CurrencyInfo.prototype.getChain = function() {
  return /** @type{?proto.xchangerpc.ChainInfo} */ (
    jspb.Message.getWrapperField(this, proto.xchangerpc.ChainInfo, 2));
};


/** @param {?proto.xchangerpc.ChainInfo|undefined} value */
proto.xchangerpc.CurrencyInfo.prototype.setChain = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.xchangerpc.CurrencyInfo.prototype.clearChain = function() {
  this.setChain(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.xchangerpc.CurrencyInfo.prototype.hasChain = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional LndInfo lnd = 3;
 * @return {?proto.xchangerpc.LndInfo}
 */
proto.xchangerpc.CurrencyInfo.prototype.getLnd = function() {
  return /** @type{?proto.xchangerpc.LndInfo} */ (
    jspb.Message.getWrapperField(this, proto.xchangerpc.LndInfo, 3));
};


/** @param {?proto.xchangerpc.LndInfo|undefined} value */
proto.xchangerpc.CurrencyInfo.prototype.setLnd = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.xchangerpc.CurrencyInfo.prototype.clearLnd = function() {
  this.setLnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.xchangerpc.CurrencyInfo.prototype.hasLnd = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xchangerpc.ChainInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xchangerpc.ChainInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.xchangerpc.ChainInfo.displayName = 'proto.xchangerpc.ChainInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xchangerpc.ChainInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.xchangerpc.ChainInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xchangerpc.ChainInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.ChainInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, 0),
    protocolversion: jspb.Message.getFieldWithDefault(msg, 2, 0),
    blocks: jspb.Message.getFieldWithDefault(msg, 3, 0),
    connections: jspb.Message.getFieldWithDefault(msg, 5, 0),
    testnet: jspb.Message.getFieldWithDefault(msg, 8, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xchangerpc.ChainInfo}
 */
proto.xchangerpc.ChainInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xchangerpc.ChainInfo;
  return proto.xchangerpc.ChainInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xchangerpc.ChainInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xchangerpc.ChainInfo}
 */
proto.xchangerpc.ChainInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProtocolversion(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBlocks(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setConnections(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTestnet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xchangerpc.ChainInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xchangerpc.ChainInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xchangerpc.ChainInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.ChainInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getProtocolversion();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getBlocks();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getConnections();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getTestnet();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
};


/**
 * optional int32 version = 1;
 * @return {number}
 */
proto.xchangerpc.ChainInfo.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.xchangerpc.ChainInfo.prototype.setVersion = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 protocolversion = 2;
 * @return {number}
 */
proto.xchangerpc.ChainInfo.prototype.getProtocolversion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.xchangerpc.ChainInfo.prototype.setProtocolversion = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int32 blocks = 3;
 * @return {number}
 */
proto.xchangerpc.ChainInfo.prototype.getBlocks = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.xchangerpc.ChainInfo.prototype.setBlocks = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional int32 connections = 5;
 * @return {number}
 */
proto.xchangerpc.ChainInfo.prototype.getConnections = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.xchangerpc.ChainInfo.prototype.setConnections = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional bool testnet = 8;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.xchangerpc.ChainInfo.prototype.getTestnet = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 8, false));
};


/** @param {boolean} value */
proto.xchangerpc.ChainInfo.prototype.setTestnet = function(value) {
  jspb.Message.setField(this, 8, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xchangerpc.LndInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xchangerpc.LndInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.xchangerpc.LndInfo.displayName = 'proto.xchangerpc.LndInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xchangerpc.LndInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.xchangerpc.LndInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xchangerpc.LndInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.LndInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, ""),
    lndchannels: (f = msg.getLndchannels()) && proto.xchangerpc.LndChannels.toObject(includeInstance, f),
    blockheight: jspb.Message.getFieldWithDefault(msg, 4, 0),
    error: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xchangerpc.LndInfo}
 */
proto.xchangerpc.LndInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xchangerpc.LndInfo;
  return proto.xchangerpc.LndInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xchangerpc.LndInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xchangerpc.LndInfo}
 */
proto.xchangerpc.LndInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 3:
      var value = new proto.xchangerpc.LndChannels;
      reader.readMessage(value,proto.xchangerpc.LndChannels.deserializeBinaryFromReader);
      msg.setLndchannels(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBlockheight(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xchangerpc.LndInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xchangerpc.LndInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xchangerpc.LndInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.LndInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLndchannels();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.xchangerpc.LndChannels.serializeBinaryToWriter
    );
  }
  f = message.getBlockheight();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getError();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string version = 1;
 * @return {string}
 */
proto.xchangerpc.LndInfo.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.xchangerpc.LndInfo.prototype.setVersion = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional LndChannels lndChannels = 3;
 * @return {?proto.xchangerpc.LndChannels}
 */
proto.xchangerpc.LndInfo.prototype.getLndchannels = function() {
  return /** @type{?proto.xchangerpc.LndChannels} */ (
    jspb.Message.getWrapperField(this, proto.xchangerpc.LndChannels, 3));
};


/** @param {?proto.xchangerpc.LndChannels|undefined} value */
proto.xchangerpc.LndInfo.prototype.setLndchannels = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.xchangerpc.LndInfo.prototype.clearLndchannels = function() {
  this.setLndchannels(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.xchangerpc.LndInfo.prototype.hasLndchannels = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 blockheight = 4;
 * @return {number}
 */
proto.xchangerpc.LndInfo.prototype.getBlockheight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.xchangerpc.LndInfo.prototype.setBlockheight = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string error = 6;
 * @return {string}
 */
proto.xchangerpc.LndInfo.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.xchangerpc.LndInfo.prototype.setError = function(value) {
  jspb.Message.setField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xchangerpc.LndChannels = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xchangerpc.LndChannels, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.xchangerpc.LndChannels.displayName = 'proto.xchangerpc.LndChannels';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xchangerpc.LndChannels.prototype.toObject = function(opt_includeInstance) {
  return proto.xchangerpc.LndChannels.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xchangerpc.LndChannels} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.LndChannels.toObject = function(includeInstance, msg) {
  var f, obj = {
    active: jspb.Message.getFieldWithDefault(msg, 1, 0),
    inactive: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pending: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xchangerpc.LndChannels}
 */
proto.xchangerpc.LndChannels.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xchangerpc.LndChannels;
  return proto.xchangerpc.LndChannels.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xchangerpc.LndChannels} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xchangerpc.LndChannels}
 */
proto.xchangerpc.LndChannels.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setActive(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInactive(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPending(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xchangerpc.LndChannels.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xchangerpc.LndChannels.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xchangerpc.LndChannels} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xchangerpc.LndChannels.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActive();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getInactive();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getPending();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional int32 active = 1;
 * @return {number}
 */
proto.xchangerpc.LndChannels.prototype.getActive = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.xchangerpc.LndChannels.prototype.setActive = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 inactive = 2;
 * @return {number}
 */
proto.xchangerpc.LndChannels.prototype.getInactive = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.xchangerpc.LndChannels.prototype.setInactive = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int32 pending = 3;
 * @return {number}
 */
proto.xchangerpc.LndChannels.prototype.getPending = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.xchangerpc.LndChannels.prototype.setPending = function(value) {
  jspb.Message.setField(this, 3, value);
};


goog.object.extend(exports, proto.xchangerpc);
